default_velocity_sacling_factor: 0.1
default_acceleration_sacling_factor: 0.1

joint_limits:
  joint_1: 
    has_valocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_2: 
    has_valocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_3: 
    has_valocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_4: 
    has_valocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint_5: 
    has_valocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0